const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.efarmz.be/wordpress/wp-content/uploads/2020/01/Pancakes.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://irecetasfaciles.com/wp-content/uploads/2019/08/pizza-de-jamon-queso-y-tocino.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'strawberry shake',
      category: 'shakes',
      price: 6.99,
      img: 'https://lacampagnola.com/uploads/recipes/5dd6bd440e6de.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://img.a1.ro/0/2017/4/15/651479/1492240260b88f9943.jpeg?w=970',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://conchaytoro.com/content/uploads/2018/08/hamburguesa-header.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://saltandbaker.com/wp-content/uploads/2020/12/New-Oreo-Milkshake-3-500x375.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.squarespace-cdn.com/content/v1/561718ebe4b062a227c4fcf2/1526955886846-X1NYVU6DV6ZX03Z3595S/ke17ZwdGBToddI8pDm48kAmzVESnndSkFo4VjUYj3iZ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UetZcyBSe8EzOZ6neXOxaly-CFnPMrhhheFAmjlN4d47pJmyJuPnROfkv0UjH_ecUA/Triglice%CC%81ridos+y+colestreol.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://cdn.pixabay.com/photo/2017/08/08/18/09/burger-2612137_960_720.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'bannana buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://img.sndimg.com/food/image/upload/q_92,fl_progressive,w_1200,c_scale/v1/img/recipes/53/69/42/Qnd4QUQTGOfG9f055sbV_0S9A4533.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.efarmz.be/wordpress/wp-content/uploads/2020/01/Pancakes.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 11,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://saltandbaker.com/wp-content/uploads/2020/12/New-Oreo-Milkshake-3-500x375.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 12,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.squarespace-cdn.com/content/v1/561718ebe4b062a227c4fcf2/1526955886846-X1NYVU6DV6ZX03Z3595S/ke17ZwdGBToddI8pDm48kAmzVESnndSkFo4VjUYj3iZ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UetZcyBSe8EzOZ6neXOxaly-CFnPMrhhheFAmjlN4d47pJmyJuPnROfkv0UjH_ecUA/Triglice%CC%81ridos+y+colestreol.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 13,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://cdn.pixabay.com/photo/2017/08/08/18/09/burger-2612137_960_720.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 14,
      title: 'bannana buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://img.sndimg.com/food/image/upload/q_92,fl_progressive,w_1200,c_scale/v1/img/recipes/53/69/42/Qnd4QUQTGOfG9f055sbV_0S9A4533.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 15,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://www.efarmz.be/wordpress/wp-content/uploads/2020/01/Pancakes.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 16,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://irecetasfaciles.com/wp-content/uploads/2019/08/pizza-de-jamon-queso-y-tocino.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 17,
      title: 'strawberry shake',
      category: 'shakes',
      price: 6.99,
      img: 'https://lacampagnola.com/uploads/recipes/5dd6bd440e6de.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 18,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://img.a1.ro/0/2017/4/15/651479/1492240260b88f9943.jpeg?w=970',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 19,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://saltandbaker.com/wp-content/uploads/2020/12/New-Oreo-Milkshake-3-500x375.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 20,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.squarespace-cdn.com/content/v1/561718ebe4b062a227c4fcf2/1526955886846-X1NYVU6DV6ZX03Z3595S/ke17ZwdGBToddI8pDm48kAmzVESnndSkFo4VjUYj3iZ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UetZcyBSe8EzOZ6neXOxaly-CFnPMrhhheFAmjlN4d47pJmyJuPnROfkv0UjH_ecUA/Triglice%CC%81ridos+y+colestreol.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 21,
      title: 'strawberry shake',
      category: 'shakes',
      price: 6.99,
      img: 'https://lacampagnola.com/uploads/recipes/5dd6bd440e6de.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
  ];
  export default menu;
